# Generated by Django 5.1.2 on 2026-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='testassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прохождения'),
        ),
    ]
