# Generated by Django 5.1.2 on 2026-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_testassignment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Время в минутах (0 - без ограничений)', verbose_name='Лимит времени'),
        ),
        migrations.AddField(
            model_name='testassignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок прохождения'),
        ),
    ]
