# Generated by Django 5.1.2 on 2026-04-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_test_time_limit_testassignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Максимальное количество попыток (0 - без ограничений)', verbose_name='Макс. попыток'),
        ),
    ]
