# Generated by Django 5.1.2 on 2026-04-18 18:22

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_test_max_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Максимальное количество попыток (0 - без ограничений)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Макс. попыток'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pass_percent',
            field=models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Проходной балл (%)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Время в минутах (0 - без ограничений)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лимит времени'),
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок прохождения'),
        ),
        migrations.AlterField(
            model_name='testassignment',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt_id',
            field=models.IntegerField(db_index=True, verbose_name='ID попытки'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['employee', 'is_completed'], name='testing_tes_employe_035687_idx'),
        ),
        migrations.AddIndex(
            model_name='testassignment',
            index=models.Index(fields=['test', 'employee'], name='testing_tes_test_id_fdaddf_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt_id', 'user'], name='testing_use_attempt_7a3855_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question', 'is_correct'], name='testing_use_questio_1edf6c_idx'),
        ),
    ]
