# Generated by Django 5.1.2 on 2026-04-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_test_is_published_alter_test_max_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('score_percent', models.IntegerField(default=0, verbose_name='Результат в %')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='testing.testassignment')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['-started_at'],
            },
        ),
    ]
